package com.emsc.entity;

// Generated 2015-1-3 9:01:28 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * SdUser generated by hbm2java
 */
@Entity
@Table(name = "sd_user", catalog = "emsc")
@XmlRootElement
public class SdUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1640195171280396184L;
 
	private Integer id;
	private String realname;
	private String username;
	private String password;

	public SdUser() {
	}

	public SdUser(String realname, String username, String password) {
		this.realname = realname;
		this.username = username;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "realname", nullable = false, length = 50)
	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
